"""Configuration module for auto-accept."""

from .constants import (
    CONFIG_DIR,
    CONFIG_FILE_PERMISSIONS,
    CONFIG_KEY_EMAIL,
    CONFIG_KEY_EMAIL_SUBJECT,
    CONFIG_KEY_LINK_TEXT,
    CONFIG_KEY_PASSWORD,
    CONFIG_KEY_PLATFORM,
    CONFIG_KEY_PLATFORM_EMAIL,
    CONFIG_KEY_PLATFORM_PASSWORD,
    CONFIGS_DIR,
    DEFAULT_SCAN_INTERVAL,
    GMAIL_IMAP_PORT,
    GMAIL_IMAP_SERVER,
    PROCESSED_EMAILS_FILE,
    SUPPORTED_PLATFORMS,
)

__all__ = [
    "GMAIL_IMAP_SERVER",
    "GMAIL_IMAP_PORT",
    "CONFIG_DIR",
    "CONFIGS_DIR",
    "PROCESSED_EMAILS_FILE",
    "DEFAULT_SCAN_INTERVAL",
    "CONFIG_FILE_PERMISSIONS",
    "CONFIG_KEY_EMAIL",
    "CONFIG_KEY_PASSWORD",
    "CONFIG_KEY_PLATFORM",
    "CONFIG_KEY_PLATFORM_EMAIL",
    "CONFIG_KEY_PLATFORM_PASSWORD",
    "CONFIG_KEY_EMAIL_SUBJECT",
    "CONFIG_KEY_LINK_TEXT",
    "SUPPORTED_PLATFORMS",
]
