name: Build & Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build Windows Executable

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Sync dependencies
        run: uv sync

      - name: Build executable
        run: |
          uv run pyinstaller --onefile --console `
            --name auto-accept `
            --hidden-import=selenium `
            --hidden-import=rich `
            --hidden-import=src `
            --hidden-import=src.core `
            --hidden-import=src.core.browser `
            --hidden-import=src.core.gmail `
            --hidden-import=src.core.scanner `
            --hidden-import=src.config `
            --hidden-import=src.config.constants `
            --hidden-import=src.utils `
            --hidden-import=src.utils.config_init `
            --hidden-import=src.utils.tracker `
            --hidden-import=src.utils.ui `
            main.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: auto-accept-windows
          path: dist/auto-accept.exe

  build-macos:
    runs-on: macos-latest
    name: Build macOS Executable

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Sync dependencies
        run: uv sync

      - name: Build executable
        run: |
          uv run pyinstaller --onefile --console \
            --name auto-accept \
            --hidden-import=selenium \
            --hidden-import=rich \
            --hidden-import=src \
            --hidden-import=src.core \
            --hidden-import=src.core.browser \
            --hidden-import=src.core.gmail \
            --hidden-import=src.core.scanner \
            --hidden-import=src.config \
            --hidden-import=src.config.constants \
            --hidden-import=src.utils \
            --hidden-import=src.utils.config_init \
            --hidden-import=src.utils.tracker \
            --hidden-import=src.utils.ui \
            main.py

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: auto-accept-macos
          path: dist/auto-accept

  release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    name: Create Release
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: auto-accept-windows
          path: dist-windows

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: auto-accept-macos
          path: dist-macos

      - name: Prepare artifacts
        run: |
          mkdir -p release
          cp dist-windows/auto-accept.exe release/auto-accept-windows.exe
          cp dist-macos/auto-accept release/auto-accept-macos
          chmod +x release/auto-accept-macos

      - name: Create checksums
        run: |
          cd release
          sha256sum auto-accept-windows.exe > auto-accept-windows.exe.sha256
          sha256sum auto-accept-macos > auto-accept-macos.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/auto-accept-windows.exe
            release/auto-accept-windows.exe.sha256
            release/auto-accept-macos
            release/auto-accept-macos.sha256
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
